// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: messages.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_UNKNOWN                             MessageType = 0
	MessageType_PRODUCE_REQUEST                     MessageType = 1
	MessageType_PRODUCE_RESPONSE                    MessageType = 2
	MessageType_CONSUME_REQUEST                     MessageType = 3
	MessageType_CONSUME_RESPONSE                    MessageType = 4
	MessageType_HEARTBEAT                           MessageType = 5
	MessageType_COMMIT_OFFSET_REQUEST               MessageType = 6
	MessageType_COMMIT_OFFSET_RESPONSE              MessageType = 7
	MessageType_FETCH_OFFSET_REQUEST                MessageType = 8
	MessageType_FETCH_OFFSET_RESPONSE               MessageType = 9
	MessageType_REQUEST_VOTE_REQUEST                MessageType = 10
	MessageType_REQUEST_VOTE_RESPONSE               MessageType = 11
	MessageType_APPEND_ENTRIES_REQUEST              MessageType = 12
	MessageType_APPEND_ENTRIES_RESPONSE             MessageType = 13
	MessageType_PRE_VOTE_REQUEST                    MessageType = 14
	MessageType_PRE_VOTE_RESPONSE                   MessageType = 15
	MessageType_NACK_REQUEST                        MessageType = 18
	MessageType_NACK_RESPONSE                       MessageType = 19
	MessageType_PRODUCE_BATCH_REQUEST               MessageType = 20
	MessageType_PRODUCE_BATCH_RESPONSE              MessageType = 21
	MessageType_SEARCH_OFFSET_BY_TIME_REQUEST       MessageType = 22
	MessageType_SEARCH_OFFSET_BY_TIME_RESPONSE      MessageType = 23
	MessageType_ATOMIC_PRODUCE_REQUEST              MessageType = 24
	MessageType_ATOMIC_PRODUCE_RESPONSE             MessageType = 25
	MessageType_REQUEST_TOPIC_OFFSETS_REQUEST       MessageType = 26
	MessageType_REQUEST_TOPIC_OFFSETS_RESPONSE      MessageType = 27
	MessageType_INCREMENTAL_SNAPSHOT_CHUNK          MessageType = 28
	MessageType_INCREMENTAL_SNAPSHOT_CHUNK_RESPONSE MessageType = 29
	MessageType_INCREMENTAL_SNAPSHOT_DONE_REQUEST   MessageType = 30
	MessageType_INCREMENTAL_SNAPSHOT_DONE_RESPONSE  MessageType = 31
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "PRODUCE_REQUEST",
		2:  "PRODUCE_RESPONSE",
		3:  "CONSUME_REQUEST",
		4:  "CONSUME_RESPONSE",
		5:  "HEARTBEAT",
		6:  "COMMIT_OFFSET_REQUEST",
		7:  "COMMIT_OFFSET_RESPONSE",
		8:  "FETCH_OFFSET_REQUEST",
		9:  "FETCH_OFFSET_RESPONSE",
		10: "REQUEST_VOTE_REQUEST",
		11: "REQUEST_VOTE_RESPONSE",
		12: "APPEND_ENTRIES_REQUEST",
		13: "APPEND_ENTRIES_RESPONSE",
		14: "PRE_VOTE_REQUEST",
		15: "PRE_VOTE_RESPONSE",
		18: "NACK_REQUEST",
		19: "NACK_RESPONSE",
		20: "PRODUCE_BATCH_REQUEST",
		21: "PRODUCE_BATCH_RESPONSE",
		22: "SEARCH_OFFSET_BY_TIME_REQUEST",
		23: "SEARCH_OFFSET_BY_TIME_RESPONSE",
		24: "ATOMIC_PRODUCE_REQUEST",
		25: "ATOMIC_PRODUCE_RESPONSE",
		26: "REQUEST_TOPIC_OFFSETS_REQUEST",
		27: "REQUEST_TOPIC_OFFSETS_RESPONSE",
		28: "INCREMENTAL_SNAPSHOT_CHUNK",
		29: "INCREMENTAL_SNAPSHOT_CHUNK_RESPONSE",
		30: "INCREMENTAL_SNAPSHOT_DONE_REQUEST",
		31: "INCREMENTAL_SNAPSHOT_DONE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"UNKNOWN":                             0,
		"PRODUCE_REQUEST":                     1,
		"PRODUCE_RESPONSE":                    2,
		"CONSUME_REQUEST":                     3,
		"CONSUME_RESPONSE":                    4,
		"HEARTBEAT":                           5,
		"COMMIT_OFFSET_REQUEST":               6,
		"COMMIT_OFFSET_RESPONSE":              7,
		"FETCH_OFFSET_REQUEST":                8,
		"FETCH_OFFSET_RESPONSE":               9,
		"REQUEST_VOTE_REQUEST":                10,
		"REQUEST_VOTE_RESPONSE":               11,
		"APPEND_ENTRIES_REQUEST":              12,
		"APPEND_ENTRIES_RESPONSE":             13,
		"PRE_VOTE_REQUEST":                    14,
		"PRE_VOTE_RESPONSE":                   15,
		"NACK_REQUEST":                        18,
		"NACK_RESPONSE":                       19,
		"PRODUCE_BATCH_REQUEST":               20,
		"PRODUCE_BATCH_RESPONSE":              21,
		"SEARCH_OFFSET_BY_TIME_REQUEST":       22,
		"SEARCH_OFFSET_BY_TIME_RESPONSE":      23,
		"ATOMIC_PRODUCE_REQUEST":              24,
		"ATOMIC_PRODUCE_RESPONSE":             25,
		"REQUEST_TOPIC_OFFSETS_REQUEST":       26,
		"REQUEST_TOPIC_OFFSETS_RESPONSE":      27,
		"INCREMENTAL_SNAPSHOT_CHUNK":          28,
		"INCREMENTAL_SNAPSHOT_CHUNK_RESPONSE": 29,
		"INCREMENTAL_SNAPSHOT_DONE_REQUEST":   30,
		"INCREMENTAL_SNAPSHOT_DONE_RESPONSE":  31,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type ErrorCode int32

const (
	ErrorCode_NONE          ErrorCode = 0
	ErrorCode_NOT_LEADER    ErrorCode = 1
	ErrorCode_UNKNOWN_ERROR ErrorCode = 99
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0:  "NONE",
		1:  "NOT_LEADER",
		99: "UNKNOWN_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"NONE":          0,
		"NOT_LEADER":    1,
		"UNKNOWN_ERROR": 99,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type ProduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Key           *string                `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceRequest) Reset() {
	*x = ProduceRequest{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceRequest) ProtoMessage() {}

func (x *ProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceRequest.ProtoReflect.Descriptor instead.
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ProduceRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProduceRequest) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ProduceRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=com.drmq.protocol.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceResponse) Reset() {
	*x = ProduceResponse{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceResponse) ProtoMessage() {}

func (x *ProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceResponse.ProtoReflect.Descriptor instead.
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ProduceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProduceResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ProduceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProduceResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_NONE
}

type ProduceBatchRequest struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Topic         string                            `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Entries       []*ProduceBatchRequest_BatchEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceBatchRequest) Reset() {
	*x = ProduceBatchRequest{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceBatchRequest) ProtoMessage() {}

func (x *ProduceBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceBatchRequest.ProtoReflect.Descriptor instead.
func (*ProduceBatchRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ProduceBatchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ProduceBatchRequest) GetEntries() []*ProduceBatchRequest_BatchEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ProduceBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseOffset    int64                  `protobuf:"varint,2,opt,name=base_offset,json=baseOffset,proto3" json:"base_offset,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,5,opt,name=error_code,json=errorCode,proto3,enum=com.drmq.protocol.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProduceBatchResponse) Reset() {
	*x = ProduceBatchResponse{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceBatchResponse) ProtoMessage() {}

func (x *ProduceBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceBatchResponse.ProtoReflect.Descriptor instead.
func (*ProduceBatchResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *ProduceBatchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProduceBatchResponse) GetBaseOffset() int64 {
	if x != nil {
		return x.BaseOffset
	}
	return 0
}

func (x *ProduceBatchResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ProduceBatchResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ProduceBatchResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_NONE
}

type AtomicBatchTopicSlice struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Topic         string                            `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Entries       []*ProduceBatchRequest_BatchEntry `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicBatchTopicSlice) Reset() {
	*x = AtomicBatchTopicSlice{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicBatchTopicSlice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicBatchTopicSlice) ProtoMessage() {}

func (x *AtomicBatchTopicSlice) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicBatchTopicSlice.ProtoReflect.Descriptor instead.
func (*AtomicBatchTopicSlice) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *AtomicBatchTopicSlice) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AtomicBatchTopicSlice) GetEntries() []*ProduceBatchRequest_BatchEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type AtomicBatchRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Slices        []*AtomicBatchTopicSlice `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicBatchRequest) Reset() {
	*x = AtomicBatchRequest{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicBatchRequest) ProtoMessage() {}

func (x *AtomicBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicBatchRequest.ProtoReflect.Descriptor instead.
func (*AtomicBatchRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *AtomicBatchRequest) GetSlices() []*AtomicBatchTopicSlice {
	if x != nil {
		return x.Slices
	}
	return nil
}

type AtomicProduceRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Slices        []*AtomicBatchTopicSlice `protobuf:"bytes,1,rep,name=slices,proto3" json:"slices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicProduceRequest) Reset() {
	*x = AtomicProduceRequest{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicProduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicProduceRequest) ProtoMessage() {}

func (x *AtomicProduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicProduceRequest.ProtoReflect.Descriptor instead.
func (*AtomicProduceRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *AtomicProduceRequest) GetSlices() []*AtomicBatchTopicSlice {
	if x != nil {
		return x.Slices
	}
	return nil
}

type AtomicProduceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	BaseOffsets   map[string]int64       `protobuf:"bytes,2,rep,name=base_offsets,json=baseOffsets,proto3" json:"base_offsets,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     ErrorCode              `protobuf:"varint,4,opt,name=error_code,json=errorCode,proto3,enum=com.drmq.protocol.ErrorCode" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AtomicProduceResponse) Reset() {
	*x = AtomicProduceResponse{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AtomicProduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AtomicProduceResponse) ProtoMessage() {}

func (x *AtomicProduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AtomicProduceResponse.ProtoReflect.Descriptor instead.
func (*AtomicProduceResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *AtomicProduceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AtomicProduceResponse) GetBaseOffsets() map[string]int64 {
	if x != nil {
		return x.BaseOffsets
	}
	return nil
}

func (x *AtomicProduceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AtomicProduceResponse) GetErrorCode() ErrorCode {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCode_NONE
}

type StoredMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Key           *string                `protobuf:"bytes,4,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StoredAt      int64                  `protobuf:"varint,6,opt,name=stored_at,json=storedAt,proto3" json:"stored_at,omitempty"`
	RaftIndex     int64                  `protobuf:"varint,7,opt,name=raft_index,json=raftIndex,proto3" json:"raft_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoredMessage) Reset() {
	*x = StoredMessage{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoredMessage) ProtoMessage() {}

func (x *StoredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoredMessage.ProtoReflect.Descriptor instead.
func (*StoredMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *StoredMessage) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StoredMessage) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *StoredMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StoredMessage) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *StoredMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *StoredMessage) GetStoredAt() int64 {
	if x != nil {
		return x.StoredAt
	}
	return 0
}

func (x *StoredMessage) GetRaftIndex() int64 {
	if x != nil {
		return x.RaftIndex
	}
	return 0
}

type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	FromOffset    int64                  `protobuf:"varint,2,opt,name=from_offset,json=fromOffset,proto3" json:"from_offset,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,3,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	TimeoutMs     int64                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	ConsumerGroup *string                `protobuf:"bytes,5,opt,name=consumer_group,json=consumerGroup,proto3,oneof" json:"consumer_group,omitempty"`
	ConsumerId    *string                `protobuf:"bytes,6,opt,name=consumer_id,json=consumerId,proto3,oneof" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *ConsumeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ConsumeRequest) GetFromOffset() int64 {
	if x != nil {
		return x.FromOffset
	}
	return 0
}

func (x *ConsumeRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

func (x *ConsumeRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *ConsumeRequest) GetConsumerGroup() string {
	if x != nil && x.ConsumerGroup != nil {
		return *x.ConsumerGroup
	}
	return ""
}

func (x *ConsumeRequest) GetConsumerId() string {
	if x != nil && x.ConsumerId != nil {
		return *x.ConsumerId
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Messages      []*StoredMessage       `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConsumeResponse) GetMessages() []*StoredMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ConsumeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CommitOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ConsumerId    *string                `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3,oneof" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetRequest) Reset() {
	*x = CommitOffsetRequest{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetRequest) ProtoMessage() {}

func (x *CommitOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetRequest.ProtoReflect.Descriptor instead.
func (*CommitOffsetRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *CommitOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *CommitOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CommitOffsetRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CommitOffsetRequest) GetConsumerId() string {
	if x != nil && x.ConsumerId != nil {
		return *x.ConsumerId
	}
	return ""
}

type CommitOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitOffsetResponse) Reset() {
	*x = CommitOffsetResponse{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitOffsetResponse) ProtoMessage() {}

func (x *CommitOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitOffsetResponse.ProtoReflect.Descriptor instead.
func (*CommitOffsetResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *CommitOffsetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommitOffsetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FetchOffsetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOffsetRequest) Reset() {
	*x = FetchOffsetRequest{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOffsetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOffsetRequest) ProtoMessage() {}

func (x *FetchOffsetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOffsetRequest.ProtoReflect.Descriptor instead.
func (*FetchOffsetRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *FetchOffsetRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *FetchOffsetRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type FetchOffsetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOffsetResponse) Reset() {
	*x = FetchOffsetResponse{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOffsetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOffsetResponse) ProtoMessage() {}

func (x *FetchOffsetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOffsetResponse.ProtoReflect.Descriptor instead.
func (*FetchOffsetResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *FetchOffsetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchOffsetResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FetchOffsetResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SearchOffsetByTimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOffsetByTimeRequest) Reset() {
	*x = SearchOffsetByTimeRequest{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOffsetByTimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOffsetByTimeRequest) ProtoMessage() {}

func (x *SearchOffsetByTimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOffsetByTimeRequest.ProtoReflect.Descriptor instead.
func (*SearchOffsetByTimeRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *SearchOffsetByTimeRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SearchOffsetByTimeRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SearchOffsetByTimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOffsetByTimeResponse) Reset() {
	*x = SearchOffsetByTimeResponse{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOffsetByTimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOffsetByTimeResponse) ProtoMessage() {}

func (x *SearchOffsetByTimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOffsetByTimeResponse.ProtoReflect.Descriptor instead.
func (*SearchOffsetByTimeResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *SearchOffsetByTimeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchOffsetByTimeResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchOffsetByTimeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConsumerGroup string                 `protobuf:"bytes,1,opt,name=consumer_group,json=consumerGroup,proto3" json:"consumer_group,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ConsumerId    *string                `protobuf:"bytes,4,opt,name=consumer_id,json=consumerId,proto3,oneof" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *NackRequest) GetConsumerGroup() string {
	if x != nil {
		return x.ConsumerGroup
	}
	return ""
}

func (x *NackRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NackRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *NackRequest) GetConsumerId() string {
	if x != nil && x.ConsumerId != nil {
		return *x.ConsumerId
	}
	return ""
}

type NackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	RoutedToDlq   bool                   `protobuf:"varint,2,opt,name=routed_to_dlq,json=routedToDlq,proto3" json:"routed_to_dlq,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackResponse) Reset() {
	*x = NackResponse{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackResponse) ProtoMessage() {}

func (x *NackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackResponse.ProtoReflect.Descriptor instead.
func (*NackResponse) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *NackResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NackResponse) GetRoutedToDlq() bool {
	if x != nil {
		return x.RoutedToDlq
	}
	return false
}

func (x *NackResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MessageEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=com.drmq.protocol.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	CorrelationId int64                  `protobuf:"varint,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageEnvelope) Reset() {
	*x = MessageEnvelope{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEnvelope) ProtoMessage() {}

func (x *MessageEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEnvelope.ProtoReflect.Descriptor instead.
func (*MessageEnvelope) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *MessageEnvelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_UNKNOWN
}

func (x *MessageEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageEnvelope) GetCorrelationId() int64 {
	if x != nil {
		return x.CorrelationId
	}
	return 0
}

type ProduceBatchRequest_BatchEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Payload         []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Key             *string                `protobuf:"bytes,2,opt,name=key,proto3,oneof" json:"key,omitempty"`
	ClientTimestamp int64                  `protobuf:"varint,3,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProduceBatchRequest_BatchEntry) Reset() {
	*x = ProduceBatchRequest_BatchEntry{}
	mi := &file_messages_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProduceBatchRequest_BatchEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProduceBatchRequest_BatchEntry) ProtoMessage() {}

func (x *ProduceBatchRequest_BatchEntry) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProduceBatchRequest_BatchEntry.ProtoReflect.Descriptor instead.
func (*ProduceBatchRequest_BatchEntry) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ProduceBatchRequest_BatchEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ProduceBatchRequest_BatchEntry) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *ProduceBatchRequest_BatchEntry) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x11com.drmq.protocol\"}\n" +
	"\x0eProduceRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x15\n" +
	"\x03key\x18\x03 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB\x06\n" +
	"\x04_key\"\xa5\x01\n" +
	"\x0fProduceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x1c.com.drmq.protocol.ErrorCodeR\terrorCode\"\xea\x01\n" +
	"\x13ProduceBatchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12K\n" +
	"\aentries\x18\x02 \x03(\v21.com.drmq.protocol.ProduceBatchRequest.BatchEntryR\aentries\x1ap\n" +
	"\n" +
	"BatchEntry\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12\x15\n" +
	"\x03key\x18\x02 \x01(\tH\x00R\x03key\x88\x01\x01\x12)\n" +
	"\x10client_timestamp\x18\x03 \x01(\x03R\x0fclientTimestampB\x06\n" +
	"\x04_key\"\xc9\x01\n" +
	"\x14ProduceBatchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vbase_offset\x18\x02 \x01(\x03R\n" +
	"baseOffset\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12;\n" +
	"\n" +
	"error_code\x18\x05 \x01(\x0e2\x1c.com.drmq.protocol.ErrorCodeR\terrorCode\"z\n" +
	"\x15AtomicBatchTopicSlice\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12K\n" +
	"\aentries\x18\x02 \x03(\v21.com.drmq.protocol.ProduceBatchRequest.BatchEntryR\aentries\"V\n" +
	"\x12AtomicBatchRequest\x12@\n" +
	"\x06slices\x18\x01 \x03(\v2(.com.drmq.protocol.AtomicBatchTopicSliceR\x06slices\"X\n" +
	"\x14AtomicProduceRequest\x12@\n" +
	"\x06slices\x18\x01 \x03(\v2(.com.drmq.protocol.AtomicBatchTopicSliceR\x06slices\"\xb1\x02\n" +
	"\x15AtomicProduceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\\\n" +
	"\fbase_offsets\x18\x02 \x03(\v29.com.drmq.protocol.AtomicProduceResponse.BaseOffsetsEntryR\vbaseOffsets\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12;\n" +
	"\n" +
	"error_code\x18\x04 \x01(\x0e2\x1c.com.drmq.protocol.ErrorCodeR\terrorCode\x1a>\n" +
	"\x10BaseOffsetsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"\xd0\x01\n" +
	"\rStoredMessage\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x15\n" +
	"\x03key\x18\x04 \x01(\tH\x00R\x03key\x88\x01\x01\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tstored_at\x18\x06 \x01(\x03R\bstoredAt\x12\x1d\n" +
	"\n" +
	"raft_index\x18\a \x01(\x03R\traftIndexB\x06\n" +
	"\x04_key\"\xfe\x01\n" +
	"\x0eConsumeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1f\n" +
	"\vfrom_offset\x18\x02 \x01(\x03R\n" +
	"fromOffset\x12!\n" +
	"\fmax_messages\x18\x03 \x01(\x05R\vmaxMessages\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x03R\ttimeoutMs\x12*\n" +
	"\x0econsumer_group\x18\x05 \x01(\tH\x00R\rconsumerGroup\x88\x01\x01\x12$\n" +
	"\vconsumer_id\x18\x06 \x01(\tH\x01R\n" +
	"consumerId\x88\x01\x01B\x11\n" +
	"\x0f_consumer_groupB\x0e\n" +
	"\f_consumer_id\"\x8e\x01\n" +
	"\x0fConsumeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12<\n" +
	"\bmessages\x18\x02 \x03(\v2 .com.drmq.protocol.StoredMessageR\bmessages\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xa0\x01\n" +
	"\x13CommitOffsetRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12$\n" +
	"\vconsumer_id\x18\x04 \x01(\tH\x00R\n" +
	"consumerId\x88\x01\x01B\x0e\n" +
	"\f_consumer_id\"U\n" +
	"\x14CommitOffsetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"Q\n" +
	"\x12FetchOffsetRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"l\n" +
	"\x13FetchOffsetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"O\n" +
	"\x19SearchOffsetByTimeRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"s\n" +
	"\x1aSearchOffsetByTimeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x98\x01\n" +
	"\vNackRequest\x12%\n" +
	"\x0econsumer_group\x18\x01 \x01(\tR\rconsumerGroup\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12$\n" +
	"\vconsumer_id\x18\x04 \x01(\tH\x00R\n" +
	"consumerId\x88\x01\x01B\x0e\n" +
	"\f_consumer_id\"q\n" +
	"\fNackResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\rrouted_to_dlq\x18\x02 \x01(\bR\vroutedToDlq\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x86\x01\n" +
	"\x0fMessageEnvelope\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.com.drmq.protocol.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\x03R\rcorrelationId*\xc1\x06\n" +
	"\vMessageType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\x13\n" +
	"\x0fPRODUCE_REQUEST\x10\x01\x12\x14\n" +
	"\x10PRODUCE_RESPONSE\x10\x02\x12\x13\n" +
	"\x0fCONSUME_REQUEST\x10\x03\x12\x14\n" +
	"\x10CONSUME_RESPONSE\x10\x04\x12\r\n" +
	"\tHEARTBEAT\x10\x05\x12\x19\n" +
	"\x15COMMIT_OFFSET_REQUEST\x10\x06\x12\x1a\n" +
	"\x16COMMIT_OFFSET_RESPONSE\x10\a\x12\x18\n" +
	"\x14FETCH_OFFSET_REQUEST\x10\b\x12\x19\n" +
	"\x15FETCH_OFFSET_RESPONSE\x10\t\x12\x18\n" +
	"\x14REQUEST_VOTE_REQUEST\x10\n" +
	"\x12\x19\n" +
	"\x15REQUEST_VOTE_RESPONSE\x10\v\x12\x1a\n" +
	"\x16APPEND_ENTRIES_REQUEST\x10\f\x12\x1b\n" +
	"\x17APPEND_ENTRIES_RESPONSE\x10\r\x12\x14\n" +
	"\x10PRE_VOTE_REQUEST\x10\x0e\x12\x15\n" +
	"\x11PRE_VOTE_RESPONSE\x10\x0f\x12\x10\n" +
	"\fNACK_REQUEST\x10\x12\x12\x11\n" +
	"\rNACK_RESPONSE\x10\x13\x12\x19\n" +
	"\x15PRODUCE_BATCH_REQUEST\x10\x14\x12\x1a\n" +
	"\x16PRODUCE_BATCH_RESPONSE\x10\x15\x12!\n" +
	"\x1dSEARCH_OFFSET_BY_TIME_REQUEST\x10\x16\x12\"\n" +
	"\x1eSEARCH_OFFSET_BY_TIME_RESPONSE\x10\x17\x12\x1a\n" +
	"\x16ATOMIC_PRODUCE_REQUEST\x10\x18\x12\x1b\n" +
	"\x17ATOMIC_PRODUCE_RESPONSE\x10\x19\x12!\n" +
	"\x1dREQUEST_TOPIC_OFFSETS_REQUEST\x10\x1a\x12\"\n" +
	"\x1eREQUEST_TOPIC_OFFSETS_RESPONSE\x10\x1b\x12\x1e\n" +
	"\x1aINCREMENTAL_SNAPSHOT_CHUNK\x10\x1c\x12'\n" +
	"#INCREMENTAL_SNAPSHOT_CHUNK_RESPONSE\x10\x1d\x12%\n" +
	"!INCREMENTAL_SNAPSHOT_DONE_REQUEST\x10\x1e\x12&\n" +
	"\"INCREMENTAL_SNAPSHOT_DONE_RESPONSE\x10\x1f*8\n" +
	"\tErrorCode\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\x01\x12\x11\n" +
	"\rUNKNOWN_ERROR\x10cB3Z1github.com/samuel025/DRMQ/drmq-go-client/protocolb\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_messages_proto_goTypes = []any{
	(MessageType)(0),                       // 0: com.drmq.protocol.MessageType
	(ErrorCode)(0),                         // 1: com.drmq.protocol.ErrorCode
	(*ProduceRequest)(nil),                 // 2: com.drmq.protocol.ProduceRequest
	(*ProduceResponse)(nil),                // 3: com.drmq.protocol.ProduceResponse
	(*ProduceBatchRequest)(nil),            // 4: com.drmq.protocol.ProduceBatchRequest
	(*ProduceBatchResponse)(nil),           // 5: com.drmq.protocol.ProduceBatchResponse
	(*AtomicBatchTopicSlice)(nil),          // 6: com.drmq.protocol.AtomicBatchTopicSlice
	(*AtomicBatchRequest)(nil),             // 7: com.drmq.protocol.AtomicBatchRequest
	(*AtomicProduceRequest)(nil),           // 8: com.drmq.protocol.AtomicProduceRequest
	(*AtomicProduceResponse)(nil),          // 9: com.drmq.protocol.AtomicProduceResponse
	(*StoredMessage)(nil),                  // 10: com.drmq.protocol.StoredMessage
	(*ConsumeRequest)(nil),                 // 11: com.drmq.protocol.ConsumeRequest
	(*ConsumeResponse)(nil),                // 12: com.drmq.protocol.ConsumeResponse
	(*CommitOffsetRequest)(nil),            // 13: com.drmq.protocol.CommitOffsetRequest
	(*CommitOffsetResponse)(nil),           // 14: com.drmq.protocol.CommitOffsetResponse
	(*FetchOffsetRequest)(nil),             // 15: com.drmq.protocol.FetchOffsetRequest
	(*FetchOffsetResponse)(nil),            // 16: com.drmq.protocol.FetchOffsetResponse
	(*SearchOffsetByTimeRequest)(nil),      // 17: com.drmq.protocol.SearchOffsetByTimeRequest
	(*SearchOffsetByTimeResponse)(nil),     // 18: com.drmq.protocol.SearchOffsetByTimeResponse
	(*NackRequest)(nil),                    // 19: com.drmq.protocol.NackRequest
	(*NackResponse)(nil),                   // 20: com.drmq.protocol.NackResponse
	(*MessageEnvelope)(nil),                // 21: com.drmq.protocol.MessageEnvelope
	(*ProduceBatchRequest_BatchEntry)(nil), // 22: com.drmq.protocol.ProduceBatchRequest.BatchEntry
	nil,                                    // 23: com.drmq.protocol.AtomicProduceResponse.BaseOffsetsEntry
}
var file_messages_proto_depIdxs = []int32{
	1,  // 0: com.drmq.protocol.ProduceResponse.error_code:type_name -> com.drmq.protocol.ErrorCode
	22, // 1: com.drmq.protocol.ProduceBatchRequest.entries:type_name -> com.drmq.protocol.ProduceBatchRequest.BatchEntry
	1,  // 2: com.drmq.protocol.ProduceBatchResponse.error_code:type_name -> com.drmq.protocol.ErrorCode
	22, // 3: com.drmq.protocol.AtomicBatchTopicSlice.entries:type_name -> com.drmq.protocol.ProduceBatchRequest.BatchEntry
	6,  // 4: com.drmq.protocol.AtomicBatchRequest.slices:type_name -> com.drmq.protocol.AtomicBatchTopicSlice
	6,  // 5: com.drmq.protocol.AtomicProduceRequest.slices:type_name -> com.drmq.protocol.AtomicBatchTopicSlice
	23, // 6: com.drmq.protocol.AtomicProduceResponse.base_offsets:type_name -> com.drmq.protocol.AtomicProduceResponse.BaseOffsetsEntry
	1,  // 7: com.drmq.protocol.AtomicProduceResponse.error_code:type_name -> com.drmq.protocol.ErrorCode
	10, // 8: com.drmq.protocol.ConsumeResponse.messages:type_name -> com.drmq.protocol.StoredMessage
	0,  // 9: com.drmq.protocol.MessageEnvelope.type:type_name -> com.drmq.protocol.MessageType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{}
	file_messages_proto_msgTypes[8].OneofWrappers = []any{}
	file_messages_proto_msgTypes[9].OneofWrappers = []any{}
	file_messages_proto_msgTypes[11].OneofWrappers = []any{}
	file_messages_proto_msgTypes[17].OneofWrappers = []any{}
	file_messages_proto_msgTypes[20].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
