// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.21.12
// source: messages.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "com.drmq.protocol";

/** --- Raft command types (for multiplexing different operations on the Raft log) --- */
export enum RaftCommandType {
  /** MESSAGE - Normal message append (default) */
  MESSAGE = 0,
  /** OFFSET_COMMIT - Consumer offset commit (replicated for durability) */
  OFFSET_COMMIT = 1,
  UNRECOGNIZED = -1,
}

export function raftCommandTypeFromJSON(object: any): RaftCommandType {
  switch (object) {
    case 0:
    case "MESSAGE":
      return RaftCommandType.MESSAGE;
    case 1:
    case "OFFSET_COMMIT":
      return RaftCommandType.OFFSET_COMMIT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return RaftCommandType.UNRECOGNIZED;
  }
}

export function raftCommandTypeToJSON(object: RaftCommandType): string {
  switch (object) {
    case RaftCommandType.MESSAGE:
      return "MESSAGE";
    case RaftCommandType.OFFSET_COMMIT:
      return "OFFSET_COMMIT";
    case RaftCommandType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum MessageType {
  UNKNOWN = 0,
  PRODUCE_REQUEST = 1,
  PRODUCE_RESPONSE = 2,
  CONSUME_REQUEST = 3,
  CONSUME_RESPONSE = 4,
  HEARTBEAT = 5,
  COMMIT_OFFSET_REQUEST = 6,
  COMMIT_OFFSET_RESPONSE = 7,
  FETCH_OFFSET_REQUEST = 8,
  FETCH_OFFSET_RESPONSE = 9,
  REQUEST_VOTE_REQUEST = 10,
  REQUEST_VOTE_RESPONSE = 11,
  APPEND_ENTRIES_REQUEST = 12,
  APPEND_ENTRIES_RESPONSE = 13,
  PRE_VOTE_REQUEST = 14,
  PRE_VOTE_RESPONSE = 15,
  INSTALL_SNAPSHOT_REQUEST = 16,
  INSTALL_SNAPSHOT_RESPONSE = 17,
  NACK_REQUEST = 18,
  NACK_RESPONSE = 19,
  UNRECOGNIZED = -1,
}

export function messageTypeFromJSON(object: any): MessageType {
  switch (object) {
    case 0:
    case "UNKNOWN":
      return MessageType.UNKNOWN;
    case 1:
    case "PRODUCE_REQUEST":
      return MessageType.PRODUCE_REQUEST;
    case 2:
    case "PRODUCE_RESPONSE":
      return MessageType.PRODUCE_RESPONSE;
    case 3:
    case "CONSUME_REQUEST":
      return MessageType.CONSUME_REQUEST;
    case 4:
    case "CONSUME_RESPONSE":
      return MessageType.CONSUME_RESPONSE;
    case 5:
    case "HEARTBEAT":
      return MessageType.HEARTBEAT;
    case 6:
    case "COMMIT_OFFSET_REQUEST":
      return MessageType.COMMIT_OFFSET_REQUEST;
    case 7:
    case "COMMIT_OFFSET_RESPONSE":
      return MessageType.COMMIT_OFFSET_RESPONSE;
    case 8:
    case "FETCH_OFFSET_REQUEST":
      return MessageType.FETCH_OFFSET_REQUEST;
    case 9:
    case "FETCH_OFFSET_RESPONSE":
      return MessageType.FETCH_OFFSET_RESPONSE;
    case 10:
    case "REQUEST_VOTE_REQUEST":
      return MessageType.REQUEST_VOTE_REQUEST;
    case 11:
    case "REQUEST_VOTE_RESPONSE":
      return MessageType.REQUEST_VOTE_RESPONSE;
    case 12:
    case "APPEND_ENTRIES_REQUEST":
      return MessageType.APPEND_ENTRIES_REQUEST;
    case 13:
    case "APPEND_ENTRIES_RESPONSE":
      return MessageType.APPEND_ENTRIES_RESPONSE;
    case 14:
    case "PRE_VOTE_REQUEST":
      return MessageType.PRE_VOTE_REQUEST;
    case 15:
    case "PRE_VOTE_RESPONSE":
      return MessageType.PRE_VOTE_RESPONSE;
    case 16:
    case "INSTALL_SNAPSHOT_REQUEST":
      return MessageType.INSTALL_SNAPSHOT_REQUEST;
    case 17:
    case "INSTALL_SNAPSHOT_RESPONSE":
      return MessageType.INSTALL_SNAPSHOT_RESPONSE;
    case 18:
    case "NACK_REQUEST":
      return MessageType.NACK_REQUEST;
    case 19:
    case "NACK_RESPONSE":
      return MessageType.NACK_RESPONSE;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MessageType.UNRECOGNIZED;
  }
}

export function messageTypeToJSON(object: MessageType): string {
  switch (object) {
    case MessageType.UNKNOWN:
      return "UNKNOWN";
    case MessageType.PRODUCE_REQUEST:
      return "PRODUCE_REQUEST";
    case MessageType.PRODUCE_RESPONSE:
      return "PRODUCE_RESPONSE";
    case MessageType.CONSUME_REQUEST:
      return "CONSUME_REQUEST";
    case MessageType.CONSUME_RESPONSE:
      return "CONSUME_RESPONSE";
    case MessageType.HEARTBEAT:
      return "HEARTBEAT";
    case MessageType.COMMIT_OFFSET_REQUEST:
      return "COMMIT_OFFSET_REQUEST";
    case MessageType.COMMIT_OFFSET_RESPONSE:
      return "COMMIT_OFFSET_RESPONSE";
    case MessageType.FETCH_OFFSET_REQUEST:
      return "FETCH_OFFSET_REQUEST";
    case MessageType.FETCH_OFFSET_RESPONSE:
      return "FETCH_OFFSET_RESPONSE";
    case MessageType.REQUEST_VOTE_REQUEST:
      return "REQUEST_VOTE_REQUEST";
    case MessageType.REQUEST_VOTE_RESPONSE:
      return "REQUEST_VOTE_RESPONSE";
    case MessageType.APPEND_ENTRIES_REQUEST:
      return "APPEND_ENTRIES_REQUEST";
    case MessageType.APPEND_ENTRIES_RESPONSE:
      return "APPEND_ENTRIES_RESPONSE";
    case MessageType.PRE_VOTE_REQUEST:
      return "PRE_VOTE_REQUEST";
    case MessageType.PRE_VOTE_RESPONSE:
      return "PRE_VOTE_RESPONSE";
    case MessageType.INSTALL_SNAPSHOT_REQUEST:
      return "INSTALL_SNAPSHOT_REQUEST";
    case MessageType.INSTALL_SNAPSHOT_RESPONSE:
      return "INSTALL_SNAPSHOT_RESPONSE";
    case MessageType.NACK_REQUEST:
      return "NACK_REQUEST";
    case MessageType.NACK_RESPONSE:
      return "NACK_RESPONSE";
    case MessageType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** Request to produce a message to a topic */
export interface ProduceRequest {
  topic: string;
  payload: Uint8Array;
  /** Optional message key for partitioning (future use) */
  key?:
    | string
    | undefined;
  /** Client-side timestamp */
  timestamp: number;
}

/** Response after producing a message */
export interface ProduceResponse {
  success: boolean;
  /** Assigned offset if successful */
  offset: number;
  /** Error details if failed */
  errorMessage: string;
}

/** Internal message representation stored in  the broker */
export interface StoredMessage {
  offset: number;
  topic: string;
  payload: Uint8Array;
  key?:
    | string
    | undefined;
  /** Original client timestamp */
  timestamp: number;
  /** Broker storage timestamp */
  storedAt: number;
}

/** Request to consume messages from a topic */
export interface ConsumeRequest {
  topic: string;
  /** Starting offset (inclusive) — ignored when consumer_group is set */
  fromOffset: number;
  /** Maximum number of messages to fetch */
  maxMessages: number;
  /** Long-poll timeout (0 = return immediately) */
  timeoutMs: number;
  /** If set, broker manages offset via group coordination */
  consumerGroup?:
    | string
    | undefined;
  /** Unique ID for this consumer instance within the group */
  consumerId?: string | undefined;
}

/** Response containing consumed messages */
export interface ConsumeResponse {
  success: boolean;
  /** List of messages */
  messages: StoredMessage[];
  /** Error details if failed */
  errorMessage: string;
}

/** Request to commit a consumer group's offset for a topic */
export interface CommitOffsetRequest {
  consumerGroup: string;
  topic: string;
  /** The next offset to read (last processed + 1) */
  offset: number;
  /** Consumer instance ID (for group coordination) */
  consumerId?: string | undefined;
}

/** Response to a commit offset request */
export interface CommitOffsetResponse {
  success: boolean;
  errorMessage: string;
}

/** Request to fetch a consumer group's committed offset for a topic */
export interface FetchOffsetRequest {
  consumerGroup: string;
  topic: string;
}

/** Response with the committed offset */
export interface FetchOffsetResponse {
  success: boolean;
  /** The committed offset, or -1 if none exists */
  offset: number;
  errorMessage: string;
}

/** Request to negatively acknowledge (NACK) a message, triggering redelivery or DLQ routing */
export interface NackRequest {
  consumerGroup: string;
  topic: string;
  /** The offset of the message being rejected */
  offset: number;
  /** Consumer instance ID (for group coordination) */
  consumerId?: string | undefined;
}

/** Response to a NACK request */
export interface NackResponse {
  success: boolean;
  /** True if the message was sent to the DLQ instead of being requeued */
  routedToDlq: boolean;
  errorMessage: string;
}

/** Envelope for TCP framing - wraps all messages with type info */
export interface MessageEnvelope {
  type: MessageType;
  /** Serialized inner message */
  payload: Uint8Array;
}

/** --- Raft log entry (wraps a user message for Raft replication) --- */
export interface RaftEntry {
  /** Term in which the entry was created */
  term: number;
  /** Position in the Raft log (1-indexed) */
  index: number;
  /** Target topic for the message */
  topic: string;
  /** Message payload */
  payload: Uint8Array;
  /** Optional message key */
  key?:
    | string
    | undefined;
  /** Client-side timestamp */
  timestamp: number;
  /** Type of command (default: MESSAGE) */
  commandType: RaftCommandType;
  /** Consumer group (for OFFSET_COMMIT) */
  consumerGroup?:
    | string
    | undefined;
  /** Offset value (for OFFSET_COMMIT) */
  offsetValue?: number | undefined;
}

/** --- Raft leader election --- */
export interface RequestVoteRequest {
  /** Candidate's term */
  term: number;
  /** Candidate requesting vote */
  candidateId: string;
  /** Index of candidate's last log entry */
  lastLogIndex: number;
  /** Term of candidate's last log entry */
  lastLogTerm: number;
}

export interface RequestVoteResponse {
  /** Current term, for candidate to update itself */
  term: number;
  /** True = vote granted */
  voteGranted: boolean;
}

/**
 * --- Raft Pre-Vote (§9.6 disruption prevention) ---
 * Sent before a real election to check if the candidate COULD win
 * without incrementing the term. Prevents restarting nodes from
 * disrupting a healthy leader.
 */
export interface PreVoteRequest {
  /** The term the candidate WOULD use (currentTerm + 1) */
  term: number;
  /** Candidate requesting pre-vote */
  candidateId: string;
  /** Index of candidate's last log entry */
  lastLogIndex: number;
  /** Term of candidate's last log entry */
  lastLogTerm: number;
}

export interface PreVoteResponse {
  /** Current term of the responder */
  term: number;
  /** True = would vote for this candidate */
  voteGranted: boolean;
}

/** --- Raft log replication (also used as heartbeat when entries is empty) --- */
export interface AppendEntriesRequest {
  /** Leader's term */
  term: number;
  /** So followers know who the leader is */
  leaderId: string;
  /** Index of log entry immediately preceding new ones */
  prevLogIndex: number;
  /** Term of prevLogIndex entry */
  prevLogTerm: number;
  /** Log entries to store (empty for heartbeat) */
  entries: RaftEntry[];
  /** Leader's commitIndex */
  leaderCommit: number;
}

export interface AppendEntriesResponse {
  /** Current term, for leader to update itself */
  term: number;
  /** True if follower contained entry matching prevLogIndex/prevLogTerm */
  success: boolean;
  /** Follower's last replicated index (for leader's matchIndex tracking) */
  matchIndex: number;
}

/** --- Raft InstallSnapshot (for followers that fell too far behind) --- */
export interface InstallSnapshotRequest {
  term: number;
  leaderId: string;
  lastIncludedIndex: number;
  lastIncludedTerm: number;
  /** Byte offset of this chunk in the file */
  offset: number;
  /** Raw zip chunk payload */
  data: Uint8Array;
  /** True if this is the final chunk */
  done: boolean;
}

export interface InstallSnapshotResponse {
  term: number;
}

function createBaseProduceRequest(): ProduceRequest {
  return { topic: "", payload: new Uint8Array(0), key: undefined, timestamp: 0 };
}

export const ProduceRequest: MessageFns<ProduceRequest> = {
  encode(message: ProduceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.topic !== "") {
      writer.uint32(10).string(message.topic);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    if (message.key !== undefined) {
      writer.uint32(26).string(message.key);
    }
    if (message.timestamp !== 0) {
      writer.uint32(32).int64(message.timestamp);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProduceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProduceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProduceRequest {
    return {
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      key: isSet(object.key) ? globalThis.String(object.key) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
    };
  },

  toJSON(message: ProduceRequest): unknown {
    const obj: any = {};
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProduceRequest>, I>>(base?: I): ProduceRequest {
    return ProduceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProduceRequest>, I>>(object: I): ProduceRequest {
    const message = createBaseProduceRequest();
    message.topic = object.topic ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    message.key = object.key ?? undefined;
    message.timestamp = object.timestamp ?? 0;
    return message;
  },
};

function createBaseProduceResponse(): ProduceResponse {
  return { success: false, offset: 0, errorMessage: "" };
}

export const ProduceResponse: MessageFns<ProduceResponse> = {
  encode(message: ProduceResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.offset !== 0) {
      writer.uint32(16).int64(message.offset);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProduceResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProduceResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProduceResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: ProduceResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProduceResponse>, I>>(base?: I): ProduceResponse {
    return ProduceResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProduceResponse>, I>>(object: I): ProduceResponse {
    const message = createBaseProduceResponse();
    message.success = object.success ?? false;
    message.offset = object.offset ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseStoredMessage(): StoredMessage {
  return { offset: 0, topic: "", payload: new Uint8Array(0), key: undefined, timestamp: 0, storedAt: 0 };
}

export const StoredMessage: MessageFns<StoredMessage> = {
  encode(message: StoredMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.offset !== 0) {
      writer.uint32(8).int64(message.offset);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    if (message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    if (message.key !== undefined) {
      writer.uint32(34).string(message.key);
    }
    if (message.timestamp !== 0) {
      writer.uint32(40).int64(message.timestamp);
    }
    if (message.storedAt !== 0) {
      writer.uint32(48).int64(message.storedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StoredMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStoredMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.offset = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.storedAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StoredMessage {
    return {
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      key: isSet(object.key) ? globalThis.String(object.key) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      storedAt: isSet(object.storedAt)
        ? globalThis.Number(object.storedAt)
        : isSet(object.stored_at)
        ? globalThis.Number(object.stored_at)
        : 0,
    };
  },

  toJSON(message: StoredMessage): unknown {
    const obj: any = {};
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.storedAt !== 0) {
      obj.storedAt = Math.round(message.storedAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StoredMessage>, I>>(base?: I): StoredMessage {
    return StoredMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StoredMessage>, I>>(object: I): StoredMessage {
    const message = createBaseStoredMessage();
    message.offset = object.offset ?? 0;
    message.topic = object.topic ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    message.key = object.key ?? undefined;
    message.timestamp = object.timestamp ?? 0;
    message.storedAt = object.storedAt ?? 0;
    return message;
  },
};

function createBaseConsumeRequest(): ConsumeRequest {
  return { topic: "", fromOffset: 0, maxMessages: 0, timeoutMs: 0, consumerGroup: undefined, consumerId: undefined };
}

export const ConsumeRequest: MessageFns<ConsumeRequest> = {
  encode(message: ConsumeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.topic !== "") {
      writer.uint32(10).string(message.topic);
    }
    if (message.fromOffset !== 0) {
      writer.uint32(16).int64(message.fromOffset);
    }
    if (message.maxMessages !== 0) {
      writer.uint32(24).int32(message.maxMessages);
    }
    if (message.timeoutMs !== 0) {
      writer.uint32(32).int64(message.timeoutMs);
    }
    if (message.consumerGroup !== undefined) {
      writer.uint32(42).string(message.consumerGroup);
    }
    if (message.consumerId !== undefined) {
      writer.uint32(50).string(message.consumerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsumeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsumeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.fromOffset = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.maxMessages = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.timeoutMs = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.consumerGroup = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.consumerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsumeRequest {
    return {
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      fromOffset: isSet(object.fromOffset)
        ? globalThis.Number(object.fromOffset)
        : isSet(object.from_offset)
        ? globalThis.Number(object.from_offset)
        : 0,
      maxMessages: isSet(object.maxMessages)
        ? globalThis.Number(object.maxMessages)
        : isSet(object.max_messages)
        ? globalThis.Number(object.max_messages)
        : 0,
      timeoutMs: isSet(object.timeoutMs)
        ? globalThis.Number(object.timeoutMs)
        : isSet(object.timeout_ms)
        ? globalThis.Number(object.timeout_ms)
        : 0,
      consumerGroup: isSet(object.consumerGroup)
        ? globalThis.String(object.consumerGroup)
        : isSet(object.consumer_group)
        ? globalThis.String(object.consumer_group)
        : undefined,
      consumerId: isSet(object.consumerId)
        ? globalThis.String(object.consumerId)
        : isSet(object.consumer_id)
        ? globalThis.String(object.consumer_id)
        : undefined,
    };
  },

  toJSON(message: ConsumeRequest): unknown {
    const obj: any = {};
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.fromOffset !== 0) {
      obj.fromOffset = Math.round(message.fromOffset);
    }
    if (message.maxMessages !== 0) {
      obj.maxMessages = Math.round(message.maxMessages);
    }
    if (message.timeoutMs !== 0) {
      obj.timeoutMs = Math.round(message.timeoutMs);
    }
    if (message.consumerGroup !== undefined) {
      obj.consumerGroup = message.consumerGroup;
    }
    if (message.consumerId !== undefined) {
      obj.consumerId = message.consumerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsumeRequest>, I>>(base?: I): ConsumeRequest {
    return ConsumeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsumeRequest>, I>>(object: I): ConsumeRequest {
    const message = createBaseConsumeRequest();
    message.topic = object.topic ?? "";
    message.fromOffset = object.fromOffset ?? 0;
    message.maxMessages = object.maxMessages ?? 0;
    message.timeoutMs = object.timeoutMs ?? 0;
    message.consumerGroup = object.consumerGroup ?? undefined;
    message.consumerId = object.consumerId ?? undefined;
    return message;
  },
};

function createBaseConsumeResponse(): ConsumeResponse {
  return { success: false, messages: [], errorMessage: "" };
}

export const ConsumeResponse: MessageFns<ConsumeResponse> = {
  encode(message: ConsumeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    for (const v of message.messages) {
      StoredMessage.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsumeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsumeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.messages.push(StoredMessage.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsumeResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      messages: globalThis.Array.isArray(object?.messages)
        ? object.messages.map((e: any) => StoredMessage.fromJSON(e))
        : [],
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: ConsumeResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.messages?.length) {
      obj.messages = message.messages.map((e) => StoredMessage.toJSON(e));
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsumeResponse>, I>>(base?: I): ConsumeResponse {
    return ConsumeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsumeResponse>, I>>(object: I): ConsumeResponse {
    const message = createBaseConsumeResponse();
    message.success = object.success ?? false;
    message.messages = object.messages?.map((e) => StoredMessage.fromPartial(e)) || [];
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseCommitOffsetRequest(): CommitOffsetRequest {
  return { consumerGroup: "", topic: "", offset: 0, consumerId: undefined };
}

export const CommitOffsetRequest: MessageFns<CommitOffsetRequest> = {
  encode(message: CommitOffsetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.consumerGroup !== "") {
      writer.uint32(10).string(message.consumerGroup);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    if (message.offset !== 0) {
      writer.uint32(24).int64(message.offset);
    }
    if (message.consumerId !== undefined) {
      writer.uint32(34).string(message.consumerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommitOffsetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommitOffsetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.consumerGroup = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offset = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.consumerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommitOffsetRequest {
    return {
      consumerGroup: isSet(object.consumerGroup)
        ? globalThis.String(object.consumerGroup)
        : isSet(object.consumer_group)
        ? globalThis.String(object.consumer_group)
        : "",
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      consumerId: isSet(object.consumerId)
        ? globalThis.String(object.consumerId)
        : isSet(object.consumer_id)
        ? globalThis.String(object.consumer_id)
        : undefined,
    };
  },

  toJSON(message: CommitOffsetRequest): unknown {
    const obj: any = {};
    if (message.consumerGroup !== "") {
      obj.consumerGroup = message.consumerGroup;
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.consumerId !== undefined) {
      obj.consumerId = message.consumerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommitOffsetRequest>, I>>(base?: I): CommitOffsetRequest {
    return CommitOffsetRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommitOffsetRequest>, I>>(object: I): CommitOffsetRequest {
    const message = createBaseCommitOffsetRequest();
    message.consumerGroup = object.consumerGroup ?? "";
    message.topic = object.topic ?? "";
    message.offset = object.offset ?? 0;
    message.consumerId = object.consumerId ?? undefined;
    return message;
  },
};

function createBaseCommitOffsetResponse(): CommitOffsetResponse {
  return { success: false, errorMessage: "" };
}

export const CommitOffsetResponse: MessageFns<CommitOffsetResponse> = {
  encode(message: CommitOffsetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.errorMessage !== "") {
      writer.uint32(18).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CommitOffsetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCommitOffsetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CommitOffsetResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: CommitOffsetResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CommitOffsetResponse>, I>>(base?: I): CommitOffsetResponse {
    return CommitOffsetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CommitOffsetResponse>, I>>(object: I): CommitOffsetResponse {
    const message = createBaseCommitOffsetResponse();
    message.success = object.success ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseFetchOffsetRequest(): FetchOffsetRequest {
  return { consumerGroup: "", topic: "" };
}

export const FetchOffsetRequest: MessageFns<FetchOffsetRequest> = {
  encode(message: FetchOffsetRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.consumerGroup !== "") {
      writer.uint32(10).string(message.consumerGroup);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchOffsetRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchOffsetRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.consumerGroup = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchOffsetRequest {
    return {
      consumerGroup: isSet(object.consumerGroup)
        ? globalThis.String(object.consumerGroup)
        : isSet(object.consumer_group)
        ? globalThis.String(object.consumer_group)
        : "",
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
    };
  },

  toJSON(message: FetchOffsetRequest): unknown {
    const obj: any = {};
    if (message.consumerGroup !== "") {
      obj.consumerGroup = message.consumerGroup;
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchOffsetRequest>, I>>(base?: I): FetchOffsetRequest {
    return FetchOffsetRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchOffsetRequest>, I>>(object: I): FetchOffsetRequest {
    const message = createBaseFetchOffsetRequest();
    message.consumerGroup = object.consumerGroup ?? "";
    message.topic = object.topic ?? "";
    return message;
  },
};

function createBaseFetchOffsetResponse(): FetchOffsetResponse {
  return { success: false, offset: 0, errorMessage: "" };
}

export const FetchOffsetResponse: MessageFns<FetchOffsetResponse> = {
  encode(message: FetchOffsetResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.offset !== 0) {
      writer.uint32(16).int64(message.offset);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FetchOffsetResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFetchOffsetResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.offset = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FetchOffsetResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: FetchOffsetResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FetchOffsetResponse>, I>>(base?: I): FetchOffsetResponse {
    return FetchOffsetResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FetchOffsetResponse>, I>>(object: I): FetchOffsetResponse {
    const message = createBaseFetchOffsetResponse();
    message.success = object.success ?? false;
    message.offset = object.offset ?? 0;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseNackRequest(): NackRequest {
  return { consumerGroup: "", topic: "", offset: 0, consumerId: undefined };
}

export const NackRequest: MessageFns<NackRequest> = {
  encode(message: NackRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.consumerGroup !== "") {
      writer.uint32(10).string(message.consumerGroup);
    }
    if (message.topic !== "") {
      writer.uint32(18).string(message.topic);
    }
    if (message.offset !== 0) {
      writer.uint32(24).int64(message.offset);
    }
    if (message.consumerId !== undefined) {
      writer.uint32(34).string(message.consumerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NackRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNackRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.consumerGroup = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.offset = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.consumerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NackRequest {
    return {
      consumerGroup: isSet(object.consumerGroup)
        ? globalThis.String(object.consumerGroup)
        : isSet(object.consumer_group)
        ? globalThis.String(object.consumer_group)
        : "",
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      consumerId: isSet(object.consumerId)
        ? globalThis.String(object.consumerId)
        : isSet(object.consumer_id)
        ? globalThis.String(object.consumer_id)
        : undefined,
    };
  },

  toJSON(message: NackRequest): unknown {
    const obj: any = {};
    if (message.consumerGroup !== "") {
      obj.consumerGroup = message.consumerGroup;
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.consumerId !== undefined) {
      obj.consumerId = message.consumerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NackRequest>, I>>(base?: I): NackRequest {
    return NackRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NackRequest>, I>>(object: I): NackRequest {
    const message = createBaseNackRequest();
    message.consumerGroup = object.consumerGroup ?? "";
    message.topic = object.topic ?? "";
    message.offset = object.offset ?? 0;
    message.consumerId = object.consumerId ?? undefined;
    return message;
  },
};

function createBaseNackResponse(): NackResponse {
  return { success: false, routedToDlq: false, errorMessage: "" };
}

export const NackResponse: MessageFns<NackResponse> = {
  encode(message: NackResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.routedToDlq !== false) {
      writer.uint32(16).bool(message.routedToDlq);
    }
    if (message.errorMessage !== "") {
      writer.uint32(26).string(message.errorMessage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NackResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNackResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.routedToDlq = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.errorMessage = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NackResponse {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      routedToDlq: isSet(object.routedToDlq)
        ? globalThis.Boolean(object.routedToDlq)
        : isSet(object.routed_to_dlq)
        ? globalThis.Boolean(object.routed_to_dlq)
        : false,
      errorMessage: isSet(object.errorMessage)
        ? globalThis.String(object.errorMessage)
        : isSet(object.error_message)
        ? globalThis.String(object.error_message)
        : "",
    };
  },

  toJSON(message: NackResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.routedToDlq !== false) {
      obj.routedToDlq = message.routedToDlq;
    }
    if (message.errorMessage !== "") {
      obj.errorMessage = message.errorMessage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NackResponse>, I>>(base?: I): NackResponse {
    return NackResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NackResponse>, I>>(object: I): NackResponse {
    const message = createBaseNackResponse();
    message.success = object.success ?? false;
    message.routedToDlq = object.routedToDlq ?? false;
    message.errorMessage = object.errorMessage ?? "";
    return message;
  },
};

function createBaseMessageEnvelope(): MessageEnvelope {
  return { type: 0, payload: new Uint8Array(0) };
}

export const MessageEnvelope: MessageFns<MessageEnvelope> = {
  encode(message: MessageEnvelope, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.payload.length !== 0) {
      writer.uint32(18).bytes(message.payload);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MessageEnvelope {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMessageEnvelope();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MessageEnvelope {
    return {
      type: isSet(object.type) ? messageTypeFromJSON(object.type) : 0,
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
    };
  },

  toJSON(message: MessageEnvelope): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = messageTypeToJSON(message.type);
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MessageEnvelope>, I>>(base?: I): MessageEnvelope {
    return MessageEnvelope.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MessageEnvelope>, I>>(object: I): MessageEnvelope {
    const message = createBaseMessageEnvelope();
    message.type = object.type ?? 0;
    message.payload = object.payload ?? new Uint8Array(0);
    return message;
  },
};

function createBaseRaftEntry(): RaftEntry {
  return {
    term: 0,
    index: 0,
    topic: "",
    payload: new Uint8Array(0),
    key: undefined,
    timestamp: 0,
    commandType: 0,
    consumerGroup: undefined,
    offsetValue: undefined,
  };
}

export const RaftEntry: MessageFns<RaftEntry> = {
  encode(message: RaftEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.index !== 0) {
      writer.uint32(16).int64(message.index);
    }
    if (message.topic !== "") {
      writer.uint32(26).string(message.topic);
    }
    if (message.payload.length !== 0) {
      writer.uint32(34).bytes(message.payload);
    }
    if (message.key !== undefined) {
      writer.uint32(42).string(message.key);
    }
    if (message.timestamp !== 0) {
      writer.uint32(48).int64(message.timestamp);
    }
    if (message.commandType !== 0) {
      writer.uint32(56).int32(message.commandType);
    }
    if (message.consumerGroup !== undefined) {
      writer.uint32(66).string(message.consumerGroup);
    }
    if (message.offsetValue !== undefined) {
      writer.uint32(72).int64(message.offsetValue);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RaftEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRaftEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.index = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.topic = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.payload = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.timestamp = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.commandType = reader.int32() as any;
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.consumerGroup = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.offsetValue = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RaftEntry {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      index: isSet(object.index) ? globalThis.Number(object.index) : 0,
      topic: isSet(object.topic) ? globalThis.String(object.topic) : "",
      payload: isSet(object.payload) ? bytesFromBase64(object.payload) : new Uint8Array(0),
      key: isSet(object.key) ? globalThis.String(object.key) : undefined,
      timestamp: isSet(object.timestamp) ? globalThis.Number(object.timestamp) : 0,
      commandType: isSet(object.commandType)
        ? raftCommandTypeFromJSON(object.commandType)
        : isSet(object.command_type)
        ? raftCommandTypeFromJSON(object.command_type)
        : 0,
      consumerGroup: isSet(object.consumerGroup)
        ? globalThis.String(object.consumerGroup)
        : isSet(object.consumer_group)
        ? globalThis.String(object.consumer_group)
        : undefined,
      offsetValue: isSet(object.offsetValue)
        ? globalThis.Number(object.offsetValue)
        : isSet(object.offset_value)
        ? globalThis.Number(object.offset_value)
        : undefined,
    };
  },

  toJSON(message: RaftEntry): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.index !== 0) {
      obj.index = Math.round(message.index);
    }
    if (message.topic !== "") {
      obj.topic = message.topic;
    }
    if (message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.key !== undefined) {
      obj.key = message.key;
    }
    if (message.timestamp !== 0) {
      obj.timestamp = Math.round(message.timestamp);
    }
    if (message.commandType !== 0) {
      obj.commandType = raftCommandTypeToJSON(message.commandType);
    }
    if (message.consumerGroup !== undefined) {
      obj.consumerGroup = message.consumerGroup;
    }
    if (message.offsetValue !== undefined) {
      obj.offsetValue = Math.round(message.offsetValue);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RaftEntry>, I>>(base?: I): RaftEntry {
    return RaftEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RaftEntry>, I>>(object: I): RaftEntry {
    const message = createBaseRaftEntry();
    message.term = object.term ?? 0;
    message.index = object.index ?? 0;
    message.topic = object.topic ?? "";
    message.payload = object.payload ?? new Uint8Array(0);
    message.key = object.key ?? undefined;
    message.timestamp = object.timestamp ?? 0;
    message.commandType = object.commandType ?? 0;
    message.consumerGroup = object.consumerGroup ?? undefined;
    message.offsetValue = object.offsetValue ?? undefined;
    return message;
  },
};

function createBaseRequestVoteRequest(): RequestVoteRequest {
  return { term: 0, candidateId: "", lastLogIndex: 0, lastLogTerm: 0 };
}

export const RequestVoteRequest: MessageFns<RequestVoteRequest> = {
  encode(message: RequestVoteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.candidateId !== "") {
      writer.uint32(18).string(message.candidateId);
    }
    if (message.lastLogIndex !== 0) {
      writer.uint32(24).int64(message.lastLogIndex);
    }
    if (message.lastLogTerm !== 0) {
      writer.uint32(32).int64(message.lastLogTerm);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestVoteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestVoteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidateId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastLogIndex = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lastLogTerm = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestVoteRequest {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      candidateId: isSet(object.candidateId)
        ? globalThis.String(object.candidateId)
        : isSet(object.candidate_id)
        ? globalThis.String(object.candidate_id)
        : "",
      lastLogIndex: isSet(object.lastLogIndex)
        ? globalThis.Number(object.lastLogIndex)
        : isSet(object.last_log_index)
        ? globalThis.Number(object.last_log_index)
        : 0,
      lastLogTerm: isSet(object.lastLogTerm)
        ? globalThis.Number(object.lastLogTerm)
        : isSet(object.last_log_term)
        ? globalThis.Number(object.last_log_term)
        : 0,
    };
  },

  toJSON(message: RequestVoteRequest): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.candidateId !== "") {
      obj.candidateId = message.candidateId;
    }
    if (message.lastLogIndex !== 0) {
      obj.lastLogIndex = Math.round(message.lastLogIndex);
    }
    if (message.lastLogTerm !== 0) {
      obj.lastLogTerm = Math.round(message.lastLogTerm);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestVoteRequest>, I>>(base?: I): RequestVoteRequest {
    return RequestVoteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestVoteRequest>, I>>(object: I): RequestVoteRequest {
    const message = createBaseRequestVoteRequest();
    message.term = object.term ?? 0;
    message.candidateId = object.candidateId ?? "";
    message.lastLogIndex = object.lastLogIndex ?? 0;
    message.lastLogTerm = object.lastLogTerm ?? 0;
    return message;
  },
};

function createBaseRequestVoteResponse(): RequestVoteResponse {
  return { term: 0, voteGranted: false };
}

export const RequestVoteResponse: MessageFns<RequestVoteResponse> = {
  encode(message: RequestVoteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.voteGranted !== false) {
      writer.uint32(16).bool(message.voteGranted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestVoteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestVoteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.voteGranted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestVoteResponse {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      voteGranted: isSet(object.voteGranted)
        ? globalThis.Boolean(object.voteGranted)
        : isSet(object.vote_granted)
        ? globalThis.Boolean(object.vote_granted)
        : false,
    };
  },

  toJSON(message: RequestVoteResponse): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.voteGranted !== false) {
      obj.voteGranted = message.voteGranted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestVoteResponse>, I>>(base?: I): RequestVoteResponse {
    return RequestVoteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestVoteResponse>, I>>(object: I): RequestVoteResponse {
    const message = createBaseRequestVoteResponse();
    message.term = object.term ?? 0;
    message.voteGranted = object.voteGranted ?? false;
    return message;
  },
};

function createBasePreVoteRequest(): PreVoteRequest {
  return { term: 0, candidateId: "", lastLogIndex: 0, lastLogTerm: 0 };
}

export const PreVoteRequest: MessageFns<PreVoteRequest> = {
  encode(message: PreVoteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.candidateId !== "") {
      writer.uint32(18).string(message.candidateId);
    }
    if (message.lastLogIndex !== 0) {
      writer.uint32(24).int64(message.lastLogIndex);
    }
    if (message.lastLogTerm !== 0) {
      writer.uint32(32).int64(message.lastLogTerm);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreVoteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreVoteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.candidateId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastLogIndex = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lastLogTerm = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreVoteRequest {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      candidateId: isSet(object.candidateId)
        ? globalThis.String(object.candidateId)
        : isSet(object.candidate_id)
        ? globalThis.String(object.candidate_id)
        : "",
      lastLogIndex: isSet(object.lastLogIndex)
        ? globalThis.Number(object.lastLogIndex)
        : isSet(object.last_log_index)
        ? globalThis.Number(object.last_log_index)
        : 0,
      lastLogTerm: isSet(object.lastLogTerm)
        ? globalThis.Number(object.lastLogTerm)
        : isSet(object.last_log_term)
        ? globalThis.Number(object.last_log_term)
        : 0,
    };
  },

  toJSON(message: PreVoteRequest): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.candidateId !== "") {
      obj.candidateId = message.candidateId;
    }
    if (message.lastLogIndex !== 0) {
      obj.lastLogIndex = Math.round(message.lastLogIndex);
    }
    if (message.lastLogTerm !== 0) {
      obj.lastLogTerm = Math.round(message.lastLogTerm);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PreVoteRequest>, I>>(base?: I): PreVoteRequest {
    return PreVoteRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PreVoteRequest>, I>>(object: I): PreVoteRequest {
    const message = createBasePreVoteRequest();
    message.term = object.term ?? 0;
    message.candidateId = object.candidateId ?? "";
    message.lastLogIndex = object.lastLogIndex ?? 0;
    message.lastLogTerm = object.lastLogTerm ?? 0;
    return message;
  },
};

function createBasePreVoteResponse(): PreVoteResponse {
  return { term: 0, voteGranted: false };
}

export const PreVoteResponse: MessageFns<PreVoteResponse> = {
  encode(message: PreVoteResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.voteGranted !== false) {
      writer.uint32(16).bool(message.voteGranted);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PreVoteResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePreVoteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.voteGranted = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PreVoteResponse {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      voteGranted: isSet(object.voteGranted)
        ? globalThis.Boolean(object.voteGranted)
        : isSet(object.vote_granted)
        ? globalThis.Boolean(object.vote_granted)
        : false,
    };
  },

  toJSON(message: PreVoteResponse): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.voteGranted !== false) {
      obj.voteGranted = message.voteGranted;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PreVoteResponse>, I>>(base?: I): PreVoteResponse {
    return PreVoteResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PreVoteResponse>, I>>(object: I): PreVoteResponse {
    const message = createBasePreVoteResponse();
    message.term = object.term ?? 0;
    message.voteGranted = object.voteGranted ?? false;
    return message;
  },
};

function createBaseAppendEntriesRequest(): AppendEntriesRequest {
  return { term: 0, leaderId: "", prevLogIndex: 0, prevLogTerm: 0, entries: [], leaderCommit: 0 };
}

export const AppendEntriesRequest: MessageFns<AppendEntriesRequest> = {
  encode(message: AppendEntriesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.leaderId !== "") {
      writer.uint32(18).string(message.leaderId);
    }
    if (message.prevLogIndex !== 0) {
      writer.uint32(24).int64(message.prevLogIndex);
    }
    if (message.prevLogTerm !== 0) {
      writer.uint32(32).int64(message.prevLogTerm);
    }
    for (const v of message.entries) {
      RaftEntry.encode(v!, writer.uint32(42).fork()).join();
    }
    if (message.leaderCommit !== 0) {
      writer.uint32(48).int64(message.leaderCommit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppendEntriesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppendEntriesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.leaderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.prevLogIndex = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.prevLogTerm = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.entries.push(RaftEntry.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.leaderCommit = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppendEntriesRequest {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      leaderId: isSet(object.leaderId)
        ? globalThis.String(object.leaderId)
        : isSet(object.leader_id)
        ? globalThis.String(object.leader_id)
        : "",
      prevLogIndex: isSet(object.prevLogIndex)
        ? globalThis.Number(object.prevLogIndex)
        : isSet(object.prev_log_index)
        ? globalThis.Number(object.prev_log_index)
        : 0,
      prevLogTerm: isSet(object.prevLogTerm)
        ? globalThis.Number(object.prevLogTerm)
        : isSet(object.prev_log_term)
        ? globalThis.Number(object.prev_log_term)
        : 0,
      entries: globalThis.Array.isArray(object?.entries)
        ? object.entries.map((e: any) => RaftEntry.fromJSON(e))
        : [],
      leaderCommit: isSet(object.leaderCommit)
        ? globalThis.Number(object.leaderCommit)
        : isSet(object.leader_commit)
        ? globalThis.Number(object.leader_commit)
        : 0,
    };
  },

  toJSON(message: AppendEntriesRequest): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.leaderId !== "") {
      obj.leaderId = message.leaderId;
    }
    if (message.prevLogIndex !== 0) {
      obj.prevLogIndex = Math.round(message.prevLogIndex);
    }
    if (message.prevLogTerm !== 0) {
      obj.prevLogTerm = Math.round(message.prevLogTerm);
    }
    if (message.entries?.length) {
      obj.entries = message.entries.map((e) => RaftEntry.toJSON(e));
    }
    if (message.leaderCommit !== 0) {
      obj.leaderCommit = Math.round(message.leaderCommit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AppendEntriesRequest>, I>>(base?: I): AppendEntriesRequest {
    return AppendEntriesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AppendEntriesRequest>, I>>(object: I): AppendEntriesRequest {
    const message = createBaseAppendEntriesRequest();
    message.term = object.term ?? 0;
    message.leaderId = object.leaderId ?? "";
    message.prevLogIndex = object.prevLogIndex ?? 0;
    message.prevLogTerm = object.prevLogTerm ?? 0;
    message.entries = object.entries?.map((e) => RaftEntry.fromPartial(e)) || [];
    message.leaderCommit = object.leaderCommit ?? 0;
    return message;
  },
};

function createBaseAppendEntriesResponse(): AppendEntriesResponse {
  return { term: 0, success: false, matchIndex: 0 };
}

export const AppendEntriesResponse: MessageFns<AppendEntriesResponse> = {
  encode(message: AppendEntriesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    if (message.matchIndex !== 0) {
      writer.uint32(24).int64(message.matchIndex);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AppendEntriesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAppendEntriesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.matchIndex = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AppendEntriesResponse {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      matchIndex: isSet(object.matchIndex)
        ? globalThis.Number(object.matchIndex)
        : isSet(object.match_index)
        ? globalThis.Number(object.match_index)
        : 0,
    };
  },

  toJSON(message: AppendEntriesResponse): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.matchIndex !== 0) {
      obj.matchIndex = Math.round(message.matchIndex);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AppendEntriesResponse>, I>>(base?: I): AppendEntriesResponse {
    return AppendEntriesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AppendEntriesResponse>, I>>(object: I): AppendEntriesResponse {
    const message = createBaseAppendEntriesResponse();
    message.term = object.term ?? 0;
    message.success = object.success ?? false;
    message.matchIndex = object.matchIndex ?? 0;
    return message;
  },
};

function createBaseInstallSnapshotRequest(): InstallSnapshotRequest {
  return {
    term: 0,
    leaderId: "",
    lastIncludedIndex: 0,
    lastIncludedTerm: 0,
    offset: 0,
    data: new Uint8Array(0),
    done: false,
  };
}

export const InstallSnapshotRequest: MessageFns<InstallSnapshotRequest> = {
  encode(message: InstallSnapshotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    if (message.leaderId !== "") {
      writer.uint32(18).string(message.leaderId);
    }
    if (message.lastIncludedIndex !== 0) {
      writer.uint32(24).int64(message.lastIncludedIndex);
    }
    if (message.lastIncludedTerm !== 0) {
      writer.uint32(32).int64(message.lastIncludedTerm);
    }
    if (message.offset !== 0) {
      writer.uint32(40).int64(message.offset);
    }
    if (message.data.length !== 0) {
      writer.uint32(50).bytes(message.data);
    }
    if (message.done !== false) {
      writer.uint32(56).bool(message.done);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstallSnapshotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstallSnapshotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.leaderId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.lastIncludedIndex = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.lastIncludedTerm = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.offset = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.data = reader.bytes();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.done = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstallSnapshotRequest {
    return {
      term: isSet(object.term) ? globalThis.Number(object.term) : 0,
      leaderId: isSet(object.leaderId)
        ? globalThis.String(object.leaderId)
        : isSet(object.leader_id)
        ? globalThis.String(object.leader_id)
        : "",
      lastIncludedIndex: isSet(object.lastIncludedIndex)
        ? globalThis.Number(object.lastIncludedIndex)
        : isSet(object.last_included_index)
        ? globalThis.Number(object.last_included_index)
        : 0,
      lastIncludedTerm: isSet(object.lastIncludedTerm)
        ? globalThis.Number(object.lastIncludedTerm)
        : isSet(object.last_included_term)
        ? globalThis.Number(object.last_included_term)
        : 0,
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      data: isSet(object.data) ? bytesFromBase64(object.data) : new Uint8Array(0),
      done: isSet(object.done) ? globalThis.Boolean(object.done) : false,
    };
  },

  toJSON(message: InstallSnapshotRequest): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    if (message.leaderId !== "") {
      obj.leaderId = message.leaderId;
    }
    if (message.lastIncludedIndex !== 0) {
      obj.lastIncludedIndex = Math.round(message.lastIncludedIndex);
    }
    if (message.lastIncludedTerm !== 0) {
      obj.lastIncludedTerm = Math.round(message.lastIncludedTerm);
    }
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    if (message.done !== false) {
      obj.done = message.done;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InstallSnapshotRequest>, I>>(base?: I): InstallSnapshotRequest {
    return InstallSnapshotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstallSnapshotRequest>, I>>(object: I): InstallSnapshotRequest {
    const message = createBaseInstallSnapshotRequest();
    message.term = object.term ?? 0;
    message.leaderId = object.leaderId ?? "";
    message.lastIncludedIndex = object.lastIncludedIndex ?? 0;
    message.lastIncludedTerm = object.lastIncludedTerm ?? 0;
    message.offset = object.offset ?? 0;
    message.data = object.data ?? new Uint8Array(0);
    message.done = object.done ?? false;
    return message;
  },
};

function createBaseInstallSnapshotResponse(): InstallSnapshotResponse {
  return { term: 0 };
}

export const InstallSnapshotResponse: MessageFns<InstallSnapshotResponse> = {
  encode(message: InstallSnapshotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.term !== 0) {
      writer.uint32(8).int64(message.term);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstallSnapshotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstallSnapshotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.term = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstallSnapshotResponse {
    return { term: isSet(object.term) ? globalThis.Number(object.term) : 0 };
  },

  toJSON(message: InstallSnapshotResponse): unknown {
    const obj: any = {};
    if (message.term !== 0) {
      obj.term = Math.round(message.term);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InstallSnapshotResponse>, I>>(base?: I): InstallSnapshotResponse {
    return InstallSnapshotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InstallSnapshotResponse>, I>>(object: I): InstallSnapshotResponse {
    const message = createBaseInstallSnapshotResponse();
    message.term = object.term ?? 0;
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
